FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY frontend/dist /usr/share/nginx/html
COPY automation/docker/nginx/default.conf.template /etc/nginx/templates/default.conf.template

ENV API_BACKEND_URL=http://127.0.0.1:3001

EXPOSE 80
