FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY front/shell/dist/shell /usr/share/nginx/html
COPY automation/docker/nginx/default.conf.template /etc/nginx/templates/default.conf.template

ENV API_BACKEND_URL=http://127.0.0.1:3001

EXPOSE 80
