services:
  nginx:
    image: nginx:alpine
    container_name: larpbabylone-nginx
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - service_objects
    networks:
      - babylone

  service_objects:
    hostname: larpbabylone_objects
    image: node:24-alpine
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    container_name: larpbabylone_objects
    env_file:
      - ${CURRENT_DIR}/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${CURRENT_DIR}:/src
      - ${CURRENT_DIR}/data:/data
    environment:
      - NODE_ENV=development
      - DATA_DIR=/data
    working_dir: /src/services/objects
    command: npm run start:dev
    networks:
      - babylone

  shell:
    image: node:24-alpine
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    container_name: larpbabylone_frontend
    hostname: larpbabylone_frontend
    env_file:
      - ${CURRENT_DIR}/.env
    volumes:
      - ${CURRENT_DIR}:/app
    environment:
      - NODE_ENV=development
    working_dir: /app/front/shell
    command: >
      npm run start -- --host 0.0.0.0 --port 80
    networks:
      - babylone

  larpbabylone_keycloack:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: larpbabylone_keycloack
    hostname: larpbabylone_keycloack
    command: start-dev
    ports:
      - "15010:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://larpbabylone_keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
    volumes:
      - ${CURRENT_DIR}/data/keycloak/data:/opt/keycloak/data
      - ${CURRENT_DIR}/data/keycloak/providers:/opt/keycloak/providers
      - ${CURRENT_DIR}/data/keycloak/themes:/opt/keycloak/themes
    networks:
      - babylone
    depends_on:
      larpbabylone_keycloak_postgres:
        condition: service_healthy

  larpbabylone_keycloak_postgres:
    image: postgres:16-alpine
    container_name: larpbabylone_keycloak_db
    hostname: larpbabylone_keycloak_db
    ports:
      - "15011:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ${CURRENT_DIR}/data/keycloak/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - babylone

networks:
  babylone:
    name: babylone
